title: "Tran Thi Hong Nhi â€“ Data Analyst"
logo: assets/img/logocv.jpg
description: >
  Ambitious Data Analyst transitioning from nearly 3 years of experience as a Credit Officer.
  Strong background in finance, risk assessment, SQL, Power BI, and Python.
  Passionate about transforming data into insights and driving business decisions.
show_downloads: false
linkedin: "https://www.linkedin.com/in/nhijulytran-analyst/"
github: "https://github.com/nhijulytran"
theme: jekyll-theme-minimal
