title: "Tran Thi Hong Nhi â€“ Data Analyst"
description: "Data Analyst | SQL | Python | BI Tools | Financial Analytics"
theme: jekyll-theme-minimal

logo: /assets/profile.jpg
show_downloads: true

google_analytics: false
markdown: kramdown
