title: "Tran Thi Hong Nhi"
description: "Aspiring Data Analyst | SQL | Python | BI Tools | Financial Analytics"
location: Ho Chi Minh City, Vietnam
theme: jekyll-theme-minimal

logo: assets/img/anhcv1.PNG
show_downloads: true

google_analytics: true
markdown: kramdown
